[package]
name = "awita_windows_bindings"
version = "0.0.1"
edition = "2018"
description = "windows bindings for awita"
license = "MIT"

[dependencies]
windows = "0.18.0"

[build-dependencies]
windows = "0.18.0"
