[package]
name = "awita_windows_bindings"
version = "0.1.0"
edition = "2018"
description = "windows bindings for awita"
license = "MIT"

[dependencies]
windows = "0.21.0"

[build-dependencies]
windows = "0.21.0"
