[package]
name = "awita"
version = "0.0.0"
edition = "2018"

[dependencies]
windows = "0.18.0"
awita_windows_bindings = { path = "../bindings" }
thiserror = "1.0.26"
gecl = "0.0.2"
num = "0.4.0"
tokio = { version = "1.9.0", features = ["rt", "sync"] }
anyhow = "1.0.42"
once_cell = "1.8.0"
serde = { version = "1.0.126", optional = true, features = ["derive"] }

[dev-dependencies]
anyhow = "1.0.42"
tokio = { version = "1.9.0", features = ["full"] }

[package.metadata.docs.rs]
targets = ["x86_64-pc-windows-msvc"]
