[package]
name = "awita"
version = "0.0.0"
edition = "2018"

[dependencies]
windows = "0.17.2"
awita_windows_bindings = { path = "../bindings" }
thiserror = "1.0.26"
gecl = "0.0.2"
num = "0.4.0"
tokio = { version = "1.8.1", features = ["rt", "sync"] }
anyhow = "1.0.42"
once_cell = "1.8.0"

[dev-dependencies]
tokio = { version = "1.8.1", features = ["full"] }
